// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/usernotificationpb/notification.proto

package usernotificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_FRIEND_REQUEST_RECEIVED       NotificationType = 1
	NotificationType_FRIEND_REQUEST_ACCEPTED       NotificationType = 2
	NotificationType_FRIEND_REQUEST_REJECTED       NotificationType = 3
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "FRIEND_REQUEST_RECEIVED",
		2: "FRIEND_REQUEST_ACCEPTED",
		3: "FRIEND_REQUEST_REJECTED",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"FRIEND_REQUEST_RECEIVED":       1,
		"FRIEND_REQUEST_ACCEPTED":       2,
		"FRIEND_REQUEST_REJECTED":       3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_usernotificationpb_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_internal_grpc_usernotificationpb_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_usernotificationpb_notification_proto_rawDescGZIP(), []int{0}
}

type SendNotificationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecipientId     int64                  `protobuf:"varint,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	SenderId        int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Type            NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	Payload         map[string]string      `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_internal_grpc_usernotificationpb_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_usernotificationpb_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_usernotificationpb_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotificationRequest) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *SendNotificationRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendNotificationRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendNotificationRequest) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_internal_grpc_usernotificationpb_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_usernotificationpb_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_usernotificationpb_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_grpc_usernotificationpb_notification_proto protoreflect.FileDescriptor

const file_internal_grpc_usernotificationpb_notification_proto_rawDesc = "" +
	"\n" +
	"3internal/grpc/usernotificationpb/notification.proto\x12\fnotification\"\xc4\x02\n" +
	"\x17SendNotificationRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\x03R\vrecipientId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x12L\n" +
	"\apayload\x18\x04 \x03(\v22.notification.SendNotificationRequest.PayloadEntryR\apayload\x12+\n" +
	"\x12created_at_unix_ms\x18\x05 \x01(\x03R\x0fcreatedAtUnixMs\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x8c\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FRIEND_REQUEST_RECEIVED\x10\x01\x12\x1b\n" +
	"\x17FRIEND_REQUEST_ACCEPTED\x10\x02\x12\x1b\n" +
	"\x17FRIEND_REQUEST_REJECTED\x10\x032x\n" +
	"\x13NotificationService\x12a\n" +
	"\x10SendNotification\x12%.notification.SendNotificationRequest\x1a&.notification.SendNotificationResponseBJZHnotification_service/internal/grpc/usernotificationpb;usernotificationpbb\x06proto3"

var (
	file_internal_grpc_usernotificationpb_notification_proto_rawDescOnce sync.Once
	file_internal_grpc_usernotificationpb_notification_proto_rawDescData []byte
)

func file_internal_grpc_usernotificationpb_notification_proto_rawDescGZIP() []byte {
	file_internal_grpc_usernotificationpb_notification_proto_rawDescOnce.Do(func() {
		file_internal_grpc_usernotificationpb_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_usernotificationpb_notification_proto_rawDesc), len(file_internal_grpc_usernotificationpb_notification_proto_rawDesc)))
	})
	return file_internal_grpc_usernotificationpb_notification_proto_rawDescData
}

var file_internal_grpc_usernotificationpb_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_usernotificationpb_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_grpc_usernotificationpb_notification_proto_goTypes = []any{
	(NotificationType)(0),            // 0: notification.NotificationType
	(*SendNotificationRequest)(nil),  // 1: notification.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 2: notification.SendNotificationResponse
	nil,                              // 3: notification.SendNotificationRequest.PayloadEntry
}
var file_internal_grpc_usernotificationpb_notification_proto_depIdxs = []int32{
	0, // 0: notification.SendNotificationRequest.type:type_name -> notification.NotificationType
	3, // 1: notification.SendNotificationRequest.payload:type_name -> notification.SendNotificationRequest.PayloadEntry
	1, // 2: notification.NotificationService.SendNotification:input_type -> notification.SendNotificationRequest
	2, // 3: notification.NotificationService.SendNotification:output_type -> notification.SendNotificationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_usernotificationpb_notification_proto_init() }
func file_internal_grpc_usernotificationpb_notification_proto_init() {
	if File_internal_grpc_usernotificationpb_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_usernotificationpb_notification_proto_rawDesc), len(file_internal_grpc_usernotificationpb_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_usernotificationpb_notification_proto_goTypes,
		DependencyIndexes: file_internal_grpc_usernotificationpb_notification_proto_depIdxs,
		EnumInfos:         file_internal_grpc_usernotificationpb_notification_proto_enumTypes,
		MessageInfos:      file_internal_grpc_usernotificationpb_notification_proto_msgTypes,
	}.Build()
	File_internal_grpc_usernotificationpb_notification_proto = out.File
	file_internal_grpc_usernotificationpb_notification_proto_goTypes = nil
	file_internal_grpc_usernotificationpb_notification_proto_depIdxs = nil
}
